// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdSI5jfICl3cUJCU2GbbIlp-Fr71aZukA',
    appId: '1:917983612150:android:b52f744ed1c3bab899f0d7',
    messagingSenderId: '917983612150',
    projectId: 'chat-app-1c070',
    storageBucket: 'chat-app-1c070.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6kuWVDtyydFGQWRcHokCDKyhi_xNA8BU',
    appId: '1:917983612150:ios:05feb1548b7e1c0c99f0d7',
    messagingSenderId: '917983612150',
    projectId: 'chat-app-1c070',
    storageBucket: 'chat-app-1c070.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5eHoDkaoOd6h3uHpVhN8D0yzpK2Gdh7U',
    appId: '1:917983612150:web:7fb522950b08503799f0d7',
    messagingSenderId: '917983612150',
    projectId: 'chat-app-1c070',
    authDomain: 'chat-app-1c070.firebaseapp.com',
    storageBucket: 'chat-app-1c070.firebasestorage.app',
    measurementId: 'G-PLGR3R7992',
  );
}
